### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Alexbaldwin94** [Alexbaldwin94/personal#1]
**Focus pages**

- [ ] Find the Best Cloud Hosting _(July)_

- [ ] Find the Best Dedicated Server Providers _(July)_

- [ ] Find the Best Windows Hosting _(July)_

- [ ] Find the Best Hosting for Drupal _(August)_

- [ ] Find the Best Email Service Provider _(August)_

- [ ] Find the Best Hosting for PHP Based Websites _(August)_

- [ ] Find Some Good & Cheap WordPress Hosting Options _(September)_

- [ ] Find Some Good & Cheap Dedicated Server Options _(September)_

- [ ] Find the Best Free Website Builder Options _(September)_

- [ ] Find the Best Free VPS Hosting Option _(September)_

**Misc**

- [ ] TLS vs SSL Article 

- [ ] Fixes of Paulius page (WP Hosting)

- [ ] Gabriel learning experience for new pages (Live composer, HTML editing for posts etc) _(July 9th)_
