### ISSUE TITLE
While Masiliauskas is off to vacation - international task list.

### ISSUE THREAD

**Issue by Masiliauskas** [Alexbaldwin94/personal#2]
- [ ] Spain - launch 'best VPN' article _(July 9th)_

- [ ] Indonesia - teach Gabriel how to do landing pages _(July 9th-10th)_

- [ ] Indonesia - launch 'best web hosting' article _(July 11th)_

- [ ] Indonesia - launch 'best VPN' article _(July 10th)_

- [ ] Spain - write the text for 'best domain registrar' article. Make sure it's suited to the locale, there are affiliate links, specific keywords. _(July 11th)_

- [ ] Spain - publish 'best domain registrar' _(July 12th)_

- [ ] Indonesia - write 'best WordPress hosting' article. Make sure it passes all the locale-specific things, as mentioned above. _(July 13th)_

- [ ] Spain - 'best WordPress hosting' article. Same stuff with locale-specific terms. _(July 16th)_

**Comment by PauliusZemaitis** [comment]
I'll be helping you with the publishing. If you have any questions make sure to send me a message :)
